name: Common configuration
description: Run jobs common for both platforms (Android and iOS)

runs:
  using: 'composite'
  steps:
    - name: Run common
      shell: bash
      run: echo "I'm on common configuration"
