name: Build and deploy app

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-app:
    name: Deploy app

    runs-on: macOS-latest

    environment:
      name: ${{ (github.ref_name == 'main') && 'production' || 'development' }}

    steps:
      - name: Checkout on branch ${{ github.ref_name }} with environment ${{ (github.ref_name == 'main') && 'production' || 'development' }}
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Configure envs
        run: |
          touch .env
          echo ENV_1=${{ secrets.ENV_1 }} > .env
          echo ENV_2=${{ secrets.ENV_2 }} >> .env
          echo ENV_3=${{ secrets.ENV_3 }} >> .env
          cat .env

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo dir=$(yarn cache dir) >> $GITHUB_OUTPUT

      - name: Restore node_modules from cache
        uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install yarn dependencies
        run: yarn install --frozen-lockfile
